name:
  connectivity-analysis-env
channels:
  - conda-forge
dependencies:
  - geopandas
  - ipykernel
  - matplotlib>=1
  - netcdf4
  - pathlib
  - pyreadr
  - python=3.12
  - rioxarray
  - shapely
  - xarray
  - ca-certificates
  - certifi
  - openssl
  - tqdm
  - pytest
  - seaborn
  - gitpython
  - pip:
    - jax[cuda12]
    - lineax
    - equinox
    - -e ./../../../jaxscape/
